### ISSUE TITLE
tutorial script failed with KeyError: u'gssapi-keyex'

### ISSUE THREAD

**Issue by Fatalerr** [knipknap/exscript#161] opened 2018-04-25 09:31 UTC
hi, 
I try the first script  in document to test the exscript on a CentOS7 but failed with 'KeyError:  u'gssapi-keyex'. I had search the keywords `exscript gssapi-keyex` in bing.com,  but got few useful info on it.  please give me a hand.

here is the scripts I wrote:
```
[root@srv ~]# cat pyexscript.py 
from Exscript.util.interact import read_login
from Exscript.protocols import SSH2

account = read_login()    # Prompt the user for his name and password
conn = SSH2(debug=9)             # We choose to use SSH2
conn.connect('localhost') # Open the SSH connection
conn.login(account)       # Authenticate on the remote host
conn.execute('uname -a')  # Execute the "uname -a" command
conn.send('exit\r')       # Send the "exit" command
conn.close()              # Wait for the connection to close
```

and the output:

> [root@srv ~]# python pyexscript.py 
Please enter your user name [root]: 
Please enter your password: 
generic: Rejecting ssh-ed25519 host key for localhost: 6eb18f4ccdef40012bad0574d30d3e24
generic: Attempting to authenticate root.
generic: auth_none failed, supported: [u'publickey', u'gssapi-keyex', u'gssapi-with-mic', u'password']
Traceback (most recent call last):
  File "pyexscript.py", line 7, in <module>
    conn.login(account)       # Authenticate on the remote host
  File "/opt/miniconda2/lib/python2.7/site-packages/Exscript/protocols/protocol.py", line 674, in login
    self.authenticate(account, flush=False)
  File "/opt/miniconda2/lib/python2.7/site-packages/Exscript/protocols/protocol.py", line 698, in authenticate
    self.protocol_authenticate(account)
  File "/opt/miniconda2/lib/python2.7/site-packages/Exscript/protocols/protocol.py", line 725, in protocol_authenticate
    self._protocol_authenticate(user, password)
  File "/opt/miniconda2/lib/python2.7/site-packages/Exscript/protocols/ssh2.py", line 338, in _protocol_authenticate
    self._paramiko_auth(user, password)
  File "/opt/miniconda2/lib/python2.7/site-packages/Exscript/protocols/ssh2.py", line 286, in _paramiko_auth
    auth_methods = self._get_auth_methods(err.allowed_types)
  File "/opt/miniconda2/lib/python2.7/site-packages/Exscript/protocols/ssh2.py", line 275, in _get_auth_methods
    for type_name in auth_types[method]:
KeyError: u'gssapi-keyex'

**Comment by anxst** [comment] 2018-05-09 18:34
I have this issue logging in to live SSH2 servers as well.

#!/usr/bin/python
import hashlib 
import Exscript
import sys
from Exscript.util.interact import read_login 
from Exscript.protocols import SSH2 


#These are the production devices. Uncomment to use in production.
#devices = ["1.1.1.1", "1.1.1.1"]
#These are the test devices. Uncomment for testing.
devices =  ["10.10.10.10"]

devicenames = ""
for device in devices:
    devicenames = devicenames + device + '_'
    print "We are deleting certs from %s." % device
    commands = ["show run"]
    commandbak = devicenames + "_output" + '.txt'
    account = read_login()
    conn = SSH2()
    conn.connect(device)
    conn.login(account)
    conn.autoinit()


Traceback:

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Scripts in Progress\cert_deletion_script\python_test.py", line 25, in <module>
    conn.login(account)
  File "C:\Python27\lib\site-packages\Exscript\protocols\protocol.py", line 670,
 in login
    self.authenticate(account, flush=False)
  File "C:\Python27\lib\site-packages\Exscript\protocols\protocol.py", line 694,
 in authenticate
    self.protocol_authenticate(account)
  File "C:\Python27\lib\site-packages\Exscript\protocols\protocol.py", line 721,
 in protocol_authenticate
    self._protocol_authenticate(user, password)
  File "C:\Python27\lib\site-packages\Exscript\protocols\ssh2.py", line 335, in
_protocol_authenticate
    self._paramiko_auth(user, password)
  File "C:\Python27\lib\site-packages\Exscript\protocols\ssh2.py", line 283, in
_paramiko_auth
    auth_methods = self._get_auth_methods(err.allowed_types)
  File "C:\Python27\lib\site-packages\Exscript\protocols\ssh2.py", line 272, in
_get_auth_methods
    for type_name in auth_types[method]:
KeyError: u'gssapi-keyex'

**Comment by knipknap** [comment] 2018-08-28 18:33
I can confirm this bug; this is because the authentication method "gssapi-keyex" is not yet supported.

http://docs.paramiko.org/en/2.4/api/ssh_gss.html

I just pushed a fix; as long as your device also supports other authentication methods, Exscript should no longer complain.

**Closed by knipknap** 2018-08-28 18:33 UTC
