### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by chikanna1** [knipknap/exscript#120] opened 2016-05-03 14:17 UTC
Anyone have success in using the python3 branch? I am getting errors with executing commands and the expect prompt

**Comment by egroeper** [comment] 2016-05-03 21:29
Sorry. No Python3 support, yet.

Closing as duplicate of #73.

**Closed by egroeper** 2016-05-03 21:29 UTC

**Comment by alexkross** [comment] 2016-05-10 09:57
I use Python3 for basic protocol support, no exscripts. Full-fledged porting is possible but boring and error-prone if not tested properly. Sorry, but have no spare time to complete.
Pull from my repo https://github.com/alexkross/exscript.git
