### ISSUE TITLE
Using Exscript with SSH forwarding (Socks tunnels)

### ISSUE THREAD

**Issue by 1001QAdotNET** [knipknap/exscript#155] opened 2017-11-21 19:21 UTC
Hi 

I am trying to use Exscript (ssh) with port forwarding and it is not quite working
Here is what I am seeing on the debug screen of my SecureCRT terminal when I enable the trace option and I run my script set to use 127.0.0.1:1080 as Socks5/5 Proxy

[LOCAL] : Starting port forward from 127.0.0.1 on local 127.0.0.1:1080 to remote 10.1.1.1:22.  
[LOCAL] : Starting port forward from 127.0.0.1 on local 127.0.0.1:1080 to remote 127.0.0.1:27800.  
[LOCAL] : Could not start port forwarding from local service 127.0.0.1:27801 to 127.0.0.1:27800.  Reason: The channel could not be opened because the connection failed.  Server error details:     Connection refused  
[LOCAL] : SEND[1]: SSH_MSG_CHANNEL_EOF 

And here is what the debug output of my script looks like

```
DEBUG:paramiko.transport:starting thread (client mode): 0x38303b0L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.1.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha1-96
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
ios: Rejecting ssh-rsa host key for host.network.mycompany.com: 3333333333333333333333
ios: Authenticating with _paramiko_auth_password
None
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
ios: Attempting to app-authenticate UserName.
ios: waiting for: ['[\\r\\n][^\\r\\n]*(?:bad secrets|denied|invalid|too short|incorrect|connection timed out|failed|failure)', 'user ?name: ?$', '(?:s\\/key|otp-md4) (\\d+) (\\S+)(?=\\s|[\\r\\n])', '(?:[\\r\\n]Password: ?|last resort password:)$', '[\\r\\n][\\-\\w+\\.:/]+(?:\\([^\\)]+\\))?[>#] ?$']
ios: Expecting a prompt
ios: Expected pattern: ["'[\\\\r\\\\n][^\\\\r\\\\n]*(?:bad secrets|denied|invalid|too short|incorrect|connection timed out|failed|failure)'", "'user ?name: ?$'", "'(?:s\\\\/key|otp-md4) (\\\\d+) (\\\\S+)(?=\\\\s|[\\\\r\\\\n])'", "'(?:[\\\\r\\\\n]Password: ?|last resort password:)$'", "'[\\\\r\\\\n][\\\\-\\\\w+\\\\.:/]+(?:\\\\([^\\\\)]+\\\\))?[>#] ?$'"]
Traceback (most recent call last):
  File "C:\Users\UserName\Documents\Eclipse\ESNetworkDiscovery\ExscriptProxy.py", line 53, in <module>
    conn.authenticate(account)
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\Exscript\protocols\Protocol.py", line 661, in authenticate
    self.app_authenticate(app_account, flush = flush)
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\Exscript\protocols\Protocol.py", line 830, in app_authenticate
    self._app_authenticate(account, password, flush, bailout)
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\Exscript\protocols\Protocol.py", line 729, in _app_authenticate
    index, match = self._waitfor(prompt_list)
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\Exscript\protocols\Protocol.py", line 946, in _waitfor
    result = self._domatch(re_list, False)
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\Exscript\protocols\SSH2.py", line 337, in _domatch
    if not self._fill_buffer():
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\Exscript\protocols\SSH2.py", line 309, in _fill_buffer
    if not self._wait_for_data():
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\Exscript\protocols\SSH2.py", line 301, in _wait_for_data
    readable, writeable, excp = select.select([self.shell], [], [], 1)
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\paramiko\channel.py", line 887, in fileno
    self._pipe = pipe.make_pipe()
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\paramiko\pipe.py", line 38, in make_pipe
    p = WindowsPipe()
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\paramiko\pipe.py", line 87, in __init__
    self._rsock.connect(('127.0.0.1', serv.getsockname()[1]))
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\socks.py", line 96, in wrapper
    return function(*args, **kwargs)
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\socks.py", line 813, in connect
    negotiate(self, dest_addr, dest_port)
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\socks.py", line 477, in _negotiate_SOCKS5
    CONNECT, dest_addr)
  File "C:\Utils\WPy2.7-32\python-2.7.13\lib\site-packages\socks.py", line 552, in _SOCKS5_request
    raise SOCKS5Error("{0:#04x}: {1}".format(status, error))
socks.SOCKS5Error: 0x05: Connection refused
DEBUG:paramiko.transport:EOF in transport thread

```

The proxy server is a Linux and it's obviously working because the script is hitting the remote device (Cisco SSH agent) 

import socks
.........
socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 1080)
socket.socket = socks.socksocket  #use the proxy socks library
conn = SSH2()    
#conn.connect_timeout=3
conn.debug=10 
conn.set_driver('ios')         # We choose to use SSH2
account = Account(name= 'Username', password = 'SecretPassword')
conn.connect('host.network.mycompany.com') # Open the SSH connection
print conn.response 
#conn.atuhenticate(account)
conn.login(account)
print conn.response
conn.execute("show cdp neighbors")
print conn.response
conn.close

**Comment by knipknap** [comment] 2017-11-21 19:36
Well, this is hard to debug from remote... can you try and set

`Exscript.protocols.ssh2._authentication_reconnect_hack = False
`
before connecting, to see if that makes a difference?

**Comment by knipknap** [comment] 2017-11-21 19:59
That is probably true, but without an identical test environment, I am probably not going to figure it out. I am **guessing** that the problem is in our handling of the shell here:

https://github.com/knipknap/exscript/blob/master/Exscript/protocols/ssh2.py#L323

But I'd have to experiment there a bit.

**Comment by 1001QAdotNET** [comment] 2017-11-21 20:02
Please let me know if I can help in any way

**Comment by 1001QAdotNET** [comment] 2017-11-21 20:06
Why am I seeing this
ios: Attempting to app-authenticate UserName

after paramiko authenticated the user ?

**Comment by knipknap** [comment] 2017-11-21 20:15
Short answer: By calling app_authenticate(), Exscript is checking the output of the remote device to see whether another authentication might be needed (as is the case on many types of devices). You can avoid this call by using protocol_authenticate() instead of login() or authenticate(), but generally it should never be required. In this case it fails, but I am sure that any other operation would also fail because the connection is just broken.

Long answer: Read this:
http://exscript.readthedocs.io/en/latest/Exscript.protocols.html#Exscript.protocols.Protocol

**Comment by 1001QAdotNET** [comment] 2017-11-21 20:24
yes that was pretty much my understanding too but I was not 100%
I am reading that  paramiko is missing the handles for SSH ProxyCommands
https://stackoverflow.com/questions/5816070/python-ssh-client-over-socks-proxy

they suggest installing https://pypi.python.org/pypi/paraproxy and they say no change to the source is required ....do you think this will fix the issue?

**Comment by knipknap** [comment] 2017-11-22 08:51
I am not really finding any info on paraproxy (except for the PyPi page), so personally I would not trust it.

This sounds like a plausible way to do it:
https://stackoverflow.com/questions/17681031/python-ssh-using-tor-proxy

However, someone with access to a socks proxy will have to provide a patch for the SSH2 adapter to support that.

**Comment by knipknap** [comment] 2017-11-22 08:54
Actually, disregard my previous comment. This is not a socks proxy, so it won't work either.

**Comment by 1001QAdotNET** [comment] 2017-11-22 15:09
I take it that this is a Paramiko issue. Do you think you can fix a workaround?
I thought I would use @ktbyers 's netmiko but his statement that netmiko supports ssh proxy is wrong that is actually SSHProxycommand which is not exactly Proxy

**Comment by knipknap** [comment] 2017-11-22 15:29
This seems like a non trivial feature request, so I can accept a patch, or I can be hired to add support. Otherwise, I am probably not going to find the time.

**Comment by 1001QAdotNET** [comment] 2017-11-22 16:12
I wish I could hire you .... but this is for personal use 
I will continue to use the jump box by changing the driver after using ssh to the device.
This would have been a nice to have feature

**Comment by knipknap** [comment] 2018-08-28 18:48
I am closing this for now. If anyone provides a patch, feel free to reopen.

**Closed by knipknap** 2018-08-28 18:48 UTC

**Comment by 1001QAdotNET** [comment] 2018-08-28 20:59
Just to be clear I think it is your implementation
Using Python socks I was able to make netmiko work using a socks proxy so I am now using netmiko

**Comment by 1001QAdotNET** [comment] 2018-08-28 21:00
nemiko has paramiko underneath and so does exscript I guess
So the issue must be in your overlay code
